# Generated by Django 5.2.8 on 2025-11-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price_cents', models.PositiveIntegerField()),
            ],
        ),
    ]
